-- Currently, it spends too much tokens even for basic tasks, so disabling it for now
return {}

-- return {
-- 	"yetone/avante.nvim",
-- 	event = "VeryLazy",
-- 	version = "0.0.25", -- Never set this value to "*"! Never!
-- 	opts = {
-- 		provider = "openai",
-- 		providers = {
-- 			openai = {
-- 				endpoint = "https://api.openai.com/v1",
-- 				model = "gpt-5",
-- 				timeout = 30000, -- Timeout in milliseconds
-- 				extra_request_body = {
-- 					temperature = 1, -- adjust if needed
-- 					max_completion_tokens = 4096,
-- 				},
-- 			},
-- 		},
-- 	},
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 		"MunifTanjim/nui.nvim",
-- 		--- The below dependencies are optional,
-- 		"echasnovski/mini.pick", -- for file_selector provider mini.pick
-- 		"nvim-telescope/telescope.nvim", -- for file_selector provider telescope
-- 		"hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
-- 		"ibhagwan/fzf-lua", -- for file_selector provider fzf
-- 		"stevearc/dressing.nvim", -- for input provider dressing
-- 		"folke/snacks.nvim", -- for input provider snacks
-- 		"nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
-- 		"zbirenbaum/copilot.lua", -- for providers='copilot'
-- 		{
-- 			-- support for image pasting
-- 			"HakonHarnes/img-clip.nvim",
-- 			event = "VeryLazy",
-- 			opts = {
-- 				-- recommended settings
-- 				default = {
-- 					embed_image_as_base64 = false,
-- 					prompt_for_file_name = false,
-- 					drag_and_drop = {
-- 						insert_mode = true,
-- 					},
-- 					-- required for Windows users
-- 					use_absolute_path = true,
-- 				},
-- 			},
-- 		},
-- 		{
-- 			-- Make sure to set this up properly if you have lazy=true
-- 			"MeanderingProgrammer/render-markdown.nvim",
-- 			opts = {
-- 				file_types = { "markdown", "Avante" },
-- 			},
-- 			ft = { "markdown", "Avante" },
-- 		},
-- 	},
-- }
